name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          extra_system_packages: "perl-file-which"
          latexmk_shell_escape: true
      - name: Archive compiled pdf
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf
