name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          extra_system_packages: "perl-file-which"
          latexmk_shell_escape: true
      - name: Checkout archive
        uses: actions/checkout@v4
        with:
          repository: andstor/archive
          token: ${{ secrets.PERSONAL_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: archive
      - name: Archive pdf
        working-directory: ./archive
        run: |
          git config --global user.name "nutsbot"
          git config --global user.email "nutsbot@users.noreply.github.com"
          repo_name=$(basename "${{ github.repository }}")
          mkdir -p "$repo_name"
          cp ../main.pdf "$repo_name/main.pdf"
          git add main.pdf
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Update main.pdf'
            git push
          fi

