name: Sync bibliography
on:
  push:
    branches:
      - main
    paths:
      - 'bibliography.bib'
      - 'software.bib'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Copy bibliography
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.
        filter: 'bibliography.bib software.bib'
        dst_owner: andstor
        dst_repo_name: bibliography
        dst_branch: main
        src_branch: main
        username: nutsbot
        email: andr3.storhaug+bot@gmail.com
