name: Sync Overleaf

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: 'main'

      - name: Sync to Overleaf
        run: |
          git config --global user.name "${{ secrets.OVERLEAF_USERNAME }}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote add overleaf https://git:${{ secrets.OVERLEAF_PASSWORD }}@git.overleaf.com/${{ secrets.OVERLEAF_REPO }}
          git fetch overleaf
          git checkout -b tmp overleaf/master
          git merge -X theirs origin/main --allow-unrelated-histories --no-edit
          git push overleaf tmp:refs/heads/master
